export default {
    EmptyGraph: {
        nodes: [],
        edges: [],
    },
    OneNodeCycle: {
        edges: [
            [1, 1, {label: 'loop'}],
        ],
    },
    TwoNodeCycle: {
        edges: [
            [1, 2],
            [2, 1],
        ],
    },
    IslandsGraph: {
        edges: [
            [10, 1],
            [1, 2],
            [1, 3],
            [6, 5],
            [2, 5],
            [5, 3],
            [4, 7],
            [4, 8],
            [4, 9],
            [4, 4],
        ],
    },
    RadialGraph: {
        edges: [
            [1, 2],
            [1, 3],
            [1, 4],
            [1, 5],
            [1, 6],
            [1, 7],
            [1, 8],
            [1, 9],
            [1, 10],
            [2, 11],
            [2, 12],
            [2, 13],
            [2, 14],
            [2, 15],
            [2, 16],
            [2, 17],
            [2, 18],
            [2, 19],
            [2, 20],
            [4, 21],
            [4, 22],
            [4, 23],
            [4, 24],
            [4, 25],
            [4, 26],
            [4, 27],
            [4, 28],
            [4, 29],
            [4, 30],
        ],
    },
    ThreeNodeCycle: {
        edges: [
            [1, 2],
            [2, 3],
            [3, 1],
        ],
    },
    FourNodeCycle: {
        edges: [
            [1, 2],
            [2, 3],
            [3, 4],
            [4, 1],
        ],
    },
    ReadmeMathExample: {
        nodes: [
            { id: 1, value: '-' },
            { id: 2, value: '+' },
            { id: 3, value: '*' },
            { id: 4, value: 45 },
            { id: 5, value: 15 },
            { id: 6, value: 9 },
            { id: 7, value: 2 },
        ],
        edges: [
            [1, 2],
            [1, 3],
            [2, 4],
            [2, 5],
            [3, 6],
            [3, 7],
        ],
    },
    UnevenTree: {
        edges: [
            [1, 2],
            [1, 3],
            [2, 4],
            [2, 5],
            [3, 6],
            [3, 7],
            [3, 8],
            [3, 9],
            [3, 10],
            [10,11],
        ],
    },
    FullAoc2020Example: {
        edges: [
            { source: 'light red', target:'bright white', count: 1 },
            { source: 'light red', target:'muted yellow', count: 2 },
            { source: 'dark orange', target:'bright white', count: 3 },
            { source: 'dark orange', target:'muted yellow', count: 4 },
            { source: 'bright white', target:'shiny gold', count: 1 },
            { source: 'muted yellow', target:'shiny gold', count: 2 },
            { source: 'muted yellow', target:'faded blue', count: 9 },
            { source: 'shiny gold', target:'dark olive', count: 1 },
            { source: 'shiny gold', target:'vibrant plum', count: 2 },
            { source: 'dark olive', target:'faded blue', count: 3 },
            { source: 'dark olive', target:'dotted black', count: 4 },
            { source: 'vibrant plum', target:'faded blue', count: 5 },
            { source: 'vibrant plum', target:'dotted black', count: 6 },
         ],
    },
};
